apiVersion: v1
kind: Pod
metadata:
  name: iot_simulator_sdk-pod0
spec:
  containers:
    - name: iot_simulator_sdk
      image: marcobevilacqua94/iot_simulator_sdk:latest
      command: ["java","-jar","iot_simulator_sdk.jar","-h","cb-example-persistent"]